baseurl = "http://localhost:1313/"
title = "Ryan Janvier"
languageCode = "en-us"
defaultContentLanguage = "en"
description = "Web developer and designer in Edmonton, Alberta"

# Pagination
paginate = 3
paginatePath = "page"

# Theme to use
theme = "hugo-material-blog"

# Copyright, appears in the footer
copyright = "© 2019 Copyright Text"

# Links format
[permalinks]
  post = "/:year/:month/:title/"

# English
[languages.en]
  languageName = "English"

  # Main menu
  [[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

  [[menu.main]]
    url = "/"
    name = "My work"
    weight = 2

  [[menu.main]]
    url = "/posts"
    name = "Blog"
    weight = 3

  [[menu.main]]
    url = "/"
    name = "Contact"
    weight = 4
